baseURL = "https://ncpr.github.io/diviner-wp-archive-theme/"
languageCode = "en-us"
title = "Diviner"
publishDir = "../"
theme = "hugo-bootstrap"
basePath = "/diviner-wp-archive-theme/"

[menu]

  [[menu.main]]
    identifier = "is-diviner-for-you"
    name = "Is Diviner Right For You?"
    pre = "<i class='fa fa-road'></i>"
    url = "is-diviner-for-you"
    weight = -100

  [[menu.main]]
      identifier = "getting-started"
      name = "Getting Started"
      pre = "<i class='fa fa-road'></i>"
      url = "getting-started"
      weight = -90

  [[menu.main]]
      identifier = "documentation"
      name = "Documentation"
      pre = "<i class='fa fa-road'></i>"
      url = "documentation"
      weight = -80

  [[menu.main]]
      identifier = "contact"
      name = "Contact"
      pre = "<i class='fa fa-road'></i>"
      url = "contact"
      weight = -50

